sudo: true

language: python
python:
  - "2.7"
  
addons:
  apt:
    packages:
    - iverilog

# command to install dependencies
install:
  - pip install myhdl myhdl_lib simplejson coverage nose

  # pihdf and to make use of the command-line tool 'module'
  - python setup.py develop

  # Create the myhdl.vpi file
  - git clone https://github.com/jandecaluwe/myhdl
  - make -C myhdl/cosimulation/icarus
  - sudo mkdir /.pihdf
  - sudo cp myhdl/cosimulation/icarus/myhdl.vpi /.pihdf

# command to run tests
script: 
#  - nosetests -vsx -w test -i "test"
  - module test/ update recursive
  - module test/ test recursive

notifications:
  email: false

