sudo: true

language: python
python:
  - "2.7"
  
addons:
  apt:
    packages:
    - iverilog

# command to install dependencies
install:
  - pip install myhdl simplejson coverage nose
  - python setup.py develop
  - git clone https://github.com/nkavaldj/myhdl_lib.git
  - python myhdl_lib/setup.py develop

#  - ./scripts/make_vpi.sh
  
# command to run tests
script: 
#  - nosetests -vsx -w test -i "test"
  - module test/ test recursive

notifications:
  email: false

